### ISSUE TITLE
DXD hold

### ISSUE THREAD

**Issue by AbuBaniaz** [LraiZer/AutoBouquets#12]
Can we  add the dxd hold function to the plugin so that any renames persist? At the moment, the one in service list change, only the ones in bouquets maintain modified names.

**Comment by LraiZer** [comment]
If it is AutoBouquets job to write and maintain the 28.2E service list, then i suggest that all services written by AB should be dxHoldName, and not just any with modified names. Maybe adult and gaming services should be set as dxIsParentalProtected by default too. 

dxHoldName=8
dxIsParentalProtected=256

**Comment by AbuBaniaz** [comment]
Well, if you have no services and just used AB 28.2, the services are added by the plugin. 

I suppose it would be easier to rename all of them instead of just the modified ones. But purists will argue against it and declare it an ugly hack.

Can we also add IEPG channel for OpenTV EPG reader? 

Is the script to zap to Sky news still working for you?

**Comment by LraiZer** [comment]
Script to zap to "Now 80's" works ok for me, it was changed from Sky News 2 years ago.

Issue has now been patched.
